### ISSUE TITLE
glad wgl generated online with --local-files differs from local

### ISSUE THREAD

**Issue by baldurk** [Dav1dde/glad-web#11]
Not sure if this is the right place to file this but it seems to be working locally so I figure it's web-specific.

I was using the online generator and I found that glad_wgl.h generated with `--local-files` isn't quite right, see [glad_wgl.h](https://glad.dav1d.de/generated/tmpYWveKxglad/glad_wgl.h) (while that file lasts) built from [this config](http://glad.dav1d.de/#specification=wgl&api=wgl%3D1.0&localfiles=on&language=c&loader=on):

```cpp
/*

    WGL loader generated by glad 0.1.27 on Mon Sep 10 13:11:26 2018.

    Language/Generator: C/C++
    Specification: wgl
    APIs: wgl=1.0
    Profile: -
    Extensions:
        
    Loader: True
    Local files: True
    Omit khrplatform: False

    Commandline:
        --api="wgl=1.0" --generator="c" --spec="wgl" --local-files --extensions=""
    Online:
        http://glad.dav1d.de/#language=c&specification=wgl&loader=on&api=wgl%3D1.0
*/

// ....

#include <glad/glad.h>
```

But if I clone the same version of glad locally it generates `#include "glad.h"` as I'd expect.

The same seems to happen with glx.

**Comment by Dav1dde** [comment]
Thanks! Fixed and deployed.
