### ISSUE TITLE
add GL, GLES, GLSC enum member to gladGLversionStruct

### ISSUE THREAD

**Issue by mean-ui-thread** [Dav1dde/glad-web#13]
for people who have run-time decisions based on which API is being used, like different shaders for example.

**Comment by Dav1dde** [comment]
You mean if they add multiple APIs at once and then load all of those at runtime? You can load only one API at once at runtime and the values in the `GLVersion` reflect the max version that was loaded for this API. If you want to check if an API was loaded you can use the top level variables, e.g.: `GLAD_GL_VERSION_X_X` and `GLAD_GL_ES_VERSION_X_X`
