### ISSUE TITLE
Emscripten support

### ISSUE THREAD

**Issue by zajo** [Dav1dde/glad-web#14]
I know there is a closed issue for this that essentially recommends not using glad on emscripten ("no loader needed"), but the best thing about glad is that the headers are the same and found in the same place across all platforms. It would be awesome if glad supports emscripten through the same API as all other platforms. Besides, the glad API has other functions, not only dynamic function lookup.

**Comment by Dav1dde** [comment]
Emscripten is supported through the same API in glad2: [emscripten example](https://github.com/Dav1dde/glad/blob/glad2/example/c/egl_gles2_glfw_emscripten.c).
