### ISSUE TITLE
`glMapBuffer` is missing from the OpenGL ES (2) header.

### ISSUE THREAD

**Issue by paulhoux** [Dav1dde/glad-web#16]
According to the [spec](http://docs.gl/gl2/glMapBuffer), `glMapBuffer` should be supported by OpenGL ES2. When generating the header, however, it is not included. Could you tell me what I am doing wrong?

To generate the files, I have used the web service with these settings:
```--profile="compatibility" --api="gles2=3.2" --generator="c" --spec="gl"```

, and included *all* the extensions.

~Paul

**Comment by Dav1dde** [comment]
The spec says it is included in OpenGL 2.0 not OpenGL ES 2, it's actually part of OpenGL 1.5.

The extension [OES_mapbuffer](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_mapbuffer.txt) does have it under the name `glMapBufferOES`.

**Comment by Dav1dde** [comment]
If you use [glad2](https://gen.glad.sh/) and enable aliasing you can actually use `glMapBuffer` and glad will take care behind the scenes to actually load `glMapBufferOES` (or whichever variant is available).

Also for issues like this please refer to the main repository over at https://github.com/Dav1dde/glad

Hope this answers your questions

**Comment by paulhoux** [comment]
Absolutely. Thanks for the quick reply.
