### ISSUE TITLE
500 Internal Server Error on generating gles2

### ISSUE THREAD

**Issue by arj-mat** [Dav1dde/glad-web#17]
Web-interface returns a 500 Internal Server Error while attempting to use GLES2 versions 3.0, 3.1 or 3.2.

**Comment by Dav1dde** [comment]
Do you have a screenshot of all the options you selected, it works for me.

**Comment by arj-mat** [comment]
![image](https://user-images.githubusercontent.com/5123733/75045422-04c9f180-54a2-11ea-9858-52702c936b53.png)

**Comment by Dav1dde** [comment]
@arj-mat thanks, should be fixed!

**Comment by arj-mat** [comment]
It's working now. Thank you.
