### ISSUE TITLE
What license should I distribute this?

### ISSUE THREAD

**Issue by ghost** [Dav1dde/glad-web#19]
Is there any license this project's generated loader files (glad.c and glad.h) are under? I want to ship my project that contains both files in the project source tree.

My project is being released under both GPLv3 and LGPLv3.

**Comment by Dav1dde** [comment]
Generally I consider the generated code public domain, see also here: https://github.com/Dav1dde/glad#whats-the-license-of-glad-generated-code

A link to the project, name etc. in the credits is appreciated but obviously up to you.
