### ISSUE TITLE
Options --local-files and --omit-khrplatform

### ISSUE THREAD

**Issue by tbastos** [Dav1dde/glad-web#2]
Hi,

As far as I can tell, glad-web doesn't expose options `--local-files` and `--omit-khrplatform`.

Is there a reason why?

Thank you!

**Comment by Dav1dde** [comment]
I haven't come around to adding them.

**Comment by Dav1dde** [comment]
Closing this now, I won't implement it for this "version". Working on a "glad2" which will have an option like this.
