### ISSUE TITLE
Date is ahead of current system time

### ISSUE THREAD

**Issue by ghost** [Dav1dde/glad-web#20]
When I recieve the zip, Make complains about clock skew detected. After looking at the files I dropped off, it says the data was last done in 2021.

Modifying the date with `touch *.h glad.c` fixes this issue.

*Note:* this could be a problem with glad, not glad-web

**Comment by Dav1dde** [comment]
Glad does not come with a makefile, also your command includes "glew" which is not related to glad at all.

The files are generated on a server with in-sync time, maybe your time is behind?

**Comment by ghost** [comment]
Hi, sorry, didn't mean to put `glew.c` but I meant `glad.c`, my head was confused. My makefile is the one that complains about it which is a commonly used tool, but it is the time that is the problem. My time seems in place, but maybe the server got my time wrong?

Here, I extracted the zip using Ark
![image](https://user-images.githubusercontent.com/56055169/109196022-3175b080-7769-11eb-8a1c-98ec39b51c49.png)

It is 12:59 PM EST as I type this
![image](https://user-images.githubusercontent.com/56055169/109196088-45211700-7769-11eb-9d5b-7c19b2622bf9.png)

**Comment by Dav1dde** [comment]
I just checked again, the server time is in sync.

I also cannot reproduce this, can you generate a new zip and share the link (e.g. `https://glad.dav1d.de/generated/tmpxzHWWEglad/`)?

The problem is just, the files get deleted every 24 hours.

**Comment by ghost** [comment]
https://glad.dav1d.de/generated/tmpzi9GLMglad/

**Comment by ghost** [comment]
it is 12:58 PM as I generated this

**Comment by Dav1dde** [comment]
Looks correct to me: 
![image](https://user-images.githubusercontent.com/255721/109396546-73058780-7932-11eb-9ad0-3b93d350357a.png)

**Comment by ghost** [comment]
Hmm, interesting... could you try switching timezones and see if you don't get same result?

**Comment by Dav1dde** [comment]
I checked the files on the disc on the server, they also all had the same timestamp, I feel like there is something wrong with your system.

**Comment by Dav1dde** [comment]
I also just checked the same zip on a Windows (Windows Explorer and 7zip), where it also reports the correct times.

**Comment by ghost** [comment]
Could you try locally changing time zones and see if it's different? I think it doesn't affect you because your timezone is the same as what you programmed it to work with.

**Comment by Dav1dde** [comment]
There is a timezone difference UTC vs CEST, even if it wasn't this code is not timezone specific at all: https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.write

The server does not use "your" time.

**Comment by ghost** [comment]
Do you think you could have the client send their current time and you can embed that into glad?

**Comment by Dav1dde** [comment]
No, this would complicate a lot of things, your zip program should be able to extract without timestamps.
