### ISSUE TITLE
WGL Undefined References

### ISSUE THREAD

**Issue by newtoncy** [Dav1dde/glad-web#22]
I choseed WGL and generated the code，but the generated file glad_ wgl. c seems to contain errors

    static int has_ext(const char *ext) {
        const char *terminator;
        const char *loc;
        const char *extensions;
    
        if(wglGetExtensionsStringEXT == NULL && wglGetExtensionsStringARB == NULL)
            return 0;
    
        if(wglGetExtensionsStringARB == NULL || GLADWGLhdc == INVALID_HANDLE_VALUE)
            extensions = wglGetExtensionsStringEXT();
        else
            extensions = wglGetExtensionsStringARB(GLADWGLhdc);
    
        if(extensions == NULL || ext == NULL)
            return 0;
    ...

identifier `wglGetExtensionsStringEXT` `wglGetExtensionsStringARB ` is undefined.

https://glad.dav1d.de/#language=c&specification=wgl&api=wgl%3D1.0&extensions=WGL_EXT_swap_control&loader=on

**Comment by Dav1dde** [comment]
Add the two extensions `WGL_ARB_extensions_string, WGL_EXT_extensions_string`, this is an unfortunate problem with WGL.
