### ISSUE TITLE
Glad header for different GL version or platform

### ISSUE THREAD

**Issue by Sologala** [Dav1dde/glad-web#25]
- Is the  source code generated with same gl version from web-service in different platform be different? 
- If the answer of last question  is no, what is the motivation that web-generator do not provide permanently source code,  be letting user's glad source file be more latest to contain new features?

BTW, i want to embedding glad source code in to my app. Like `glfw`, I fetch is use cmake `FeachContent` from git repo, compile and link locally. 
- Is there some way to detect current driver and determine the relative GL version?
- Is there some way to automatically down the glad loader generating web? some web interface which use `GET` `SET`.

**Comment by Dav1dde** [comment]
The generated code is the same for every platform.

You should generate the code once and check the files in directly with your other source code, only re-generate when you actually need to. There is no benefit in re-generating on every build.

> Is there some way to detect current driver and determine the relative GL version?

You can figure this out by creating probing with GL contexts, create the highest possible which does not fail, but this is irrelevant for glad, you generate the code you want to target and then deal with it at runtime.

> Is there some way to automatically down the glad loader generating web? some web interface which use GET SET.

No, if you try to automate this, there is a high chance you will get IP banned by Cloudflare.

**Comment by Sologala** [comment]
@Dav1dde  Thks for explaination.
