### ISSUE TITLE
OpenGL ES loader not invoked

### ISSUE THREAD

**Issue by jeannekamikaze** [Dav1dde/glad-web#4]
Hi, I would like to get some clarification regarding the loading of OpenGL ES function pointers. Please note that this may not be a bug and just a misunderstanding on my side.

I have generated a loader from your website with the following settings:

```
Language: C/C++
Specification: OpenGL
Profile: Core
gl: Version 4.5
gles1: None
gles2: Version 3.1
glsc2: None
Extensions: None
```

When I then open an OpenGL ES 3.1 context and call gladLoadGL(), I notice that glad_glDispatchCompute is unresolved:

```
printf("Address of glad_glDispatchCompute: %p\n", glad_glDispatchCompute); // (nil)
```

A closer look at the generate glad.c file reveals that the OpenGL ES loader is not called:

```
int gladLoadGL(void) {
    int status = 0;

    if(open_gl()) {
        status = gladLoadGLLoader(&get_proc);
        close_gl();
    }

    return status;
}
```

If however I replace the call to gladLoadGLLoader() to gladLoadGLES2Loader(), then I do get glad_glDispatchCompute resolved to a correct address:

```
int gladLoadGL(void) {
    int status = 0;

    if(open_gl()) {
        //status = gladLoadGLLoader(&get_proc);
        status = gladLoadGLES2Loader(&get_proc);
        close_gl();
    }

    return status;
}
```

```
Address of glad_glDispatchCompute: 0x7f3ae8d09580
```

Can you help clarify what is the expected behaviour here? If I open an OpenGL ES context, shouldn't glad call the OpenGL ES loader?

Given that glad is calling the GL loader and not the GL ES loader, I have also tried generating a loader with no gl version (only gles2):

```
Language: C/C++
Specification: OpenGL
Profile: Core
gl: none
gles1: None
gles2: Version 3.1
glsc2: None
Extensions: None
```

However, if I generate such a loader, I cannot even compile the generated files.

Please clarify if this is a bug in the loader generator or a misunderstanding on my side.

Thanks.

**Comment by Dav1dde** [comment]
Loading OpenGL and OpenGL at the same time is not possible,  so you need to decide to load either at runtime. 
This version of glad only includes a loader for OpenGL (not GLES),  so in order to load GLES you need to call `gladLoadGLESLoader` with a loader which is able to retrieve OpenGLES function pointers yourself (e.g. `eglGetProcAddress`, `glfwGetProcAddress`...).
