### ISSUE TITLE
Non-interactive generator

### ISSUE THREAD

**Issue by FlorianRhiem** [Dav1dde/glad-web#5]
Hello, thank you for glad and this web frontend!

For build scripts it would be nice to have a URL from which to download the correct glad version instead of including the generated code in the project's repository. Right now, non-interactive use would require a script to send a post request and get the proper URL from there, which is not hard, but a lot less comfortable than just generating a URL which could then be used e.g. in CMake's ExternalProject_Add directive.

You already support "Permalinks" to pre-fill the form, like this one:
http://glad.dav1d.de/#profile=core&specification=gl&api=gl%3D3.3&api=gles1%3Dnone&api=gles2%3Dnone&api=glsc2%3Dnone&language=c&loader=on

Would you be willing to support a similar url that would directly lead to the zip file?

There's a huge number of possible configurations for glad, so I understand that you cannot persistently host all combinations. Generating the zip files on the fly and caching them should be alright though.

**Comment by Dav1dde** [comment]
I considered it and decided against it, the intended way to use glad is to download the files once and just drop them into your project. If you need to add an additional extension, just generate new files (e.g. using the "autofill" link) and replace your old ones.

Keeping the generated files is just too much effort for me, I don't want to "spam" my servers harddisk with ~50-100 folders/zips daily (which can sum up to ~50-75MiB). It also has the problem of people directly linking to these zips resulting in increased traffic for me (minor issue) and it may result in dead links once I need to start removing files or the server crashes/hdd faults.

All in all I don't see a big enough benefit, what would be your usecase, or what prevents you from integrating glad directly into your project?
