### ISSUE TITLE
Add support for OpenGL in Rust.

### ISSUE THREAD

**Issue by AraHaan** [Dav1dde/glad-web#7]
Rust as a programming language is growing rapidly. It would be nice if there way a way to be able to Add all versions of OpenGL in glad to rust. By Far glad is perfect for my needs for the Intel GM45 that is in my Inspiron 1545 that actually does not crash on me when I compile. I know of a few games that uses OpenGL newer than 2.1 that causes the crash. Otherwise good work on being able to select version 2.1 on the website that suits my needs.

**Comment by Dav1dde** [comment]
Hey, thanks for the Feedback, I created a new issue for Rust over on the main generator project, once the generator supports it it will also show up on the website: https://github.com/Dav1dde/glad/issues/80.

But I don't think I will have much time in the near future to work on Rust support, but I will keep it on my todo.

**Comment by AraHaan** [comment]
btw on the website on the KHR thing are they all the same no matter what version of opengl is selected?

Also you should make it to where if opengl is selected that gles cannot be. Basically make gles only for module devices like phones. Otherwise people will confuse them for dektop computers / laptops that can have MAc, linux, or Windows on it (which would fail for them when they try to use the compiled output and crash).

**Comment by Dav1dde** [comment]
> btw on the website on the KHR thing are they all the same no matter what version of opengl is selected?

What do you mean, the specification? Yes.

OpenGL ES also exists on Windows, Linux and MAC. And it does not crash when you select the option together with OpenGL.

**Comment by AraHaan** [comment]
ah, then I was told wrong then. :laughing:
