### ISSUE TITLE
Add Nim support

### ISSUE THREAD

**Issue by johnnovak** [Dav1dde/glad-web#8]
I attempted to do it myself but the README is not sufficiently detailed enough for someone who is not familiar with Python web development like myself and I don't want to invest the time to learn it because it would be a one-off thing for me...

Alternatively, I could make a PR "blind" containing the changes and then you could test it etc... But the necessary changes seem to be quite trivial, probably a half an hour job anyway...

**Comment by Dav1dde** [comment]
Sorry it took so long. Nim has been added in https://github.com/Dav1dde/glad-web/commit/fdfbf70621ec0f7375862f22c95389fbb392447c.

It's live on the [website](http://glad.dav1d.de) - please let me know if something doesn't work as expected.

**Comment by johnnovak** [comment]
Great! Thanks, I'll check it out soon.
