### ISSUE TITLE
Can't omit khrplatform?

### ISSUE THREAD

**Issue by mcclure** [Dav1dde/glad-web#9]
When I look in the files generated by GLAD web, I see the line:

    Omit khrplatform: False

glad.c also always has:

    #include <KHR/khrplatform.h>

As far as I can tell I don't need this file, I certainly don't use it. Every time I emit GLAD I manually delete the "#include khrplatform" line.

The line in the header comments implies that GLAD has the ability to omit the khrplatform include. Could this ability be exposed in the web interface? I see no such button currently.

**Comment by Dav1dde** [comment]
Initially the plan was to properly do the inclusion in glad2 and not back port it. Now it's over a year later ... I just added it to the website.
